# Generated by Django 5.2.5 on 2025-10-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO_ASISTEN', 'No asisten')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemApp.mesa')),
            ],
        ),
    ]
