# Generated by Django 5.2.5 on 2026-07-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemApp', '0002_alter_mesa_capacidad_alter_mesa_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reservas/'),
        ),
    ]
